#!/bin/sh
#
# Trove used to run a version of Lorry Controller that wasn't a
# daemon, but instead was invoked once a minute from a crontab owned
# by the lorry user. When we upgrade to a version of Lorry Controller
# that does run as a daemon, we need to disable the cronjob. This
# script does that.
#
# The lorry user crontab may contain other jobs, so we can't just
# willy-nilly delete the whole crontab. Instead, we remove the
# specific line. The line looks like this:
#
#     */1 * * * * flock -x -n /home/lorry/lorry-controller-area/lockfile
#     -c lorry-controller --work-area=/home/lorry/lorry-controller-area 
#     --log=syslog --log-level=info --html-file=/home/lorry/lc-status.html
#
# Except, of course, all on one line.


crontab -l |
grep -v -e '-c lorry-controller' |
crontab -
